name: Documentation

on:
  push:
    branches:
      - main # update to match your development branch (master, main, dev, trunk, ...)
    tags: '*'
  pull_request:

jobs:
  build:
    # These permissions are needed to:
    # - Deploy the documentation: https://documenter.juliadocs.org/stable/man/hosting/#Permissions
    # - Delete old caches: https://github.com/julia-actions/cache#usage
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: |
          sudo apt-get update && \
            sudo apt-get install --no-install-recommends -qq texlive-fonts-recommended git \
            texlive-luatex texlive-pictures texlive-latex-extra pdf2svg lmodern \
            poppler-utils gnuplot-nox wget ca-certificates openssh-client rsync file
      - run: |
          julia --project=docs -e '
            using Documenter: doctest, DocMeta
            using Coefplots
            DocMeta.setdocmeta!(Coefplots, :DocTestSetup, :(using Coefplots); recursive=true)
            doctest(Coefplots)'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}